version: "2"
services:
  redis:
    image: redis:3.2.5-alpine
    networks:
      - demo-net
  app:
      image: flin/page-hit-counter:v2
    ports:
      - 5000:5000
    depends_on:
      - redis
    networks:
      - demo-net
networks:
  demo-net:
    external: true
